#### 1. Import des librairies

In [16]:
import pandas as pd
import numpy as np

#### 2. Import des données

In [17]:
data = pd.read_excel("/Users/arthurlenet/Desktop/structured_products/data/reporting.xlsx", sheet_name="Data")
data

           Date  XS1732593444
0    2018-07-02    100.000000
1    2018-07-03     97.712839
2    2018-07-04     96.430602
3    2018-07-05     94.105209
4    2018-07-06     94.230126
...         ...           ...
2087 2026-08-18     88.625727
2088 2026-08-19     87.348993
2089 2026-08-20     87.526000
2090 2026-08-21     87.077626
2091 2026-08-24     86.500000

[2092 rows x 2 columns]

#### 1. Date d'évaluation de remboursement anticipée : min 1 an après, semestrielle

In [18]:
calendar_json = [
    {
        "n": 1,
        "Evaluation Date": "2019-07-02",
        "Redemption Date": "2019-07-16"
    },
    {
        "n": 2,
        "Evaluation Date": "2020-01-02",
        "Redemption Date": "2020-01-16"
    },
    {
        "n": 3,
        "Evaluation Date": "2020-07-02",
        "Redemption Date": "2020-07-16"
    },
    {
        "n": 4,
        "Evaluation Date": "2021-01-04",
        "Redemption Date": "2021-01-18"
    },
    {
        "n": 5,
        "Evaluation Date": "2021-07-02",
        "Redemption Date": "2021-07-16"
    },
    {
        "n": 6,
        "Evaluation Date": "2022-01-03",
        "Redemption Date": "2022-01-17"
    },
    {
        "n": 7,
        "Evaluation Date": "2022-07-04",
        "Redemption Date": "2022-07-18"
    },
    {
        "n": 8,
        "Evaluation Date": "2023-01-02",
        "Redemption Date": "2023-01-16"
    },
    {
        "n": 9,
        "Evaluation Date": "2023-07-03",
        "Redemption Date": "2023-07-17"
    },
    {
        "n": 10,
        "Evaluation Date": "2024-01-02",
        "Redemption Date": "2024-01-16"
    },
    {
        "n": 11,
        "Evaluation Date": "2024-07-02",
        "Redemption Date": "2024-07-16"
    },
    {
        "n": 12,
        "Evaluation Date": "2025-01-02",
        "Redemption Date": "2025-01-16"
    },
    {
        "n": 13,
        "Evaluation Date": "2025-07-02",
        "Redemption Date": "2025-07-16"
    },
    {
        "n": 14,
        "Evaluation Date": "2026-01-02",
        "Redemption Date": "2026-01-16"
    },
    {
        "n": 15,
        "Evaluation Date": "2026-07-02",
        "Redemption Date": "2026-07-16"
    },
    {
        "n": 16,
        "Evaluation Date": "2027-01-04",
        "Redemption Date": "2027-01-18"
    },
    {
        "n": 17,
        "Evaluation Date": "2027-07-02",
        "Redemption Date": "2027-07-16"
    },
    {
        "n": 18,
        "Evaluation Date": "2028-01-03",
        "Redemption Date": "2028-01-17"
    }
]

In [19]:
import pandas as pd

calendar = pd.DataFrame(calendar_json)

# Conversion des colonnes de dates au format datetime
calendar["Evaluation Date"] = pd.to_datetime(
    calendar["Evaluation Date"]
)

calendar["Redemption Date"] = pd.to_datetime(
    calendar["Redemption Date"]
)

# calendar = calendar.drop(columns=["n"])

calendar

     n Evaluation Date Redemption Date
0    1      2019-07-02      2019-07-16
1    2      2020-01-02      2020-01-16
2    3      2020-07-02      2020-07-16
3    4      2021-01-04      2021-01-18
4    5      2021-07-02      2021-07-16
5    6      2022-01-03      2022-01-17
6    7      2022-07-04      2022-07-18
7    8      2023-01-02      2023-01-16
8    9      2023-07-03      2023-07-17
9   10      2024-01-02      2024-01-16
10  11      2024-07-02      2024-07-16
11  12      2025-01-02      2025-01-16
12  13      2025-07-02      2025-07-16
13  14      2026-01-02      2026-01-16
14  15      2026-07-02      2026-07-16
15  16      2027-01-04      2027-01-18
16  17      2027-07-02      2027-07-16
17  18      2028-01-03      2028-01-17

#### 3. Enregistrement

In [20]:
# Ajout d'une nouvelle sheet dans le fichier Excel existant reporting
path = "/Users/arthurlenet/Desktop/structured_products/data/reporting.xlsx"

with pd.ExcelWriter(path, engine="openpyxl", mode="a", if_sheet_exists="replace") as writer:
    calendar.to_excel(writer, sheet_name="Calendar", index=False)